command:
- ${interpreter}
- ${program}
- ${args_no_boolean_flags}
program: main.py
name: llama-cnndm-val-fw-bloop
method: grid
metric:
  goal: maximize
  name: bart_score_prob
parameters:
  model:
    value: meta-llama/Llama-3.1-8B-Instruct
    #google/gemma-2-9b-it
    #mistralai/Mistral-Nemo-Instruct-2407
    #meta-llama/Llama-3.1-8B-Instruct
  dataset:
    value: cnndm
    #values: [cnndm, multinews, xsum, scitldr-abs, scitldr-aic, scitldr-full]
  split:
    value: validation
  subsample:
    value: 0.1
  max_input_len:
    value: 4096 # 4096 for llama, 64000 for mistral, 2048 for gemma
  beam_width:
    value: 8 # 12 for llama, 5 for mistral, 4 for gemma
  alpha:
    values: [-1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5, 3] # 3 for llama, 4 for mistral, 6 for gemma
  use_fw:
    value: True
